### ISSUE TITLE
Module build failed (from ./node_modules/babel-loader/lib/index.js)

### ISSUE THREAD

**Issue by ZhangTaoK** [LLK/scratchjr#285]
Error build：

ERROR in ./src/entry/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react-native" relative to directory "/Users/xx/Desktop"

**Comment by ZhangTaoK** [comment]
ERROR in ./src/entry/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react-native" relative to directory "/Users/xxx/Desktop"
    at /Users/xxx/Desktop/RNProject/scratchjr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/xxx/Desktop/RNProject/scratchjr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/xxx/Desktop/RNProject/scratchjr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/xxx/Desktop/RNProject/scratchjr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/xxx/Desktop/RNProject/scratchjr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/xxx/Desktop/RNProject/scratchjr/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/xxx/Desktop/RNProject/scratchjr/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/xxx/Desktop/RNProject/scratchjr/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/xxx/Desktop/RNProject/scratchjr/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/xxx/Desktop/RNProject/scratchjr/node_modules/babel-loader/lib/index.js:173:20)

> Task :app:generateWebpackBundle FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateWebpackBundle'.
> Process 'command './bundle-compile.sh'' finished with non-zero exit value 2

**Comment by ZhangTaoK** [comment]
以上问题为build项目时发生错误，报错信息集中在“babel-loader”上，通过 https://github.com/babel/babel-loader/issues/149 找的解决方法：
在package.json中添加
`"babel": {
    "presets": [
      "es2015"
    ]
  }`
即可解决上述问题。

**Comment by ZhangTaoK** [comment]
解决后，现在我将关闭这个问题。
