### ISSUE TITLE
Android - Fatal Exception: SQLiteCantOpenDatabaseException

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratchjr#88]
Unhandled SQLLite exception when resuming the main Scratch Jr activity. Seems isolated to `Android 4.4`.

```
java.lang.RuntimeException: Unable to resume activity {org.scratchjr.android/org.scratchjr.android.ScratchJrActivity}: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3196)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3225)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2612)
    at android.app.ActivityThread.access$900(ActivityThread.java:174)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5756)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
    at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:338)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:232)
    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:892)
    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:862)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:699)
    at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1331)
    at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
    at org.scratchjr.android.DatabaseManager.open(DatabaseManager.java:52)
    at org.scratchjr.android.ScratchJrActivity.onResume(ScratchJrActivity.java:183)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1198)
    at android.app.Activity.performResume(Activity.java:5688)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3186)
```

Related to LLK/scratchjr-private#469

---

Moved from LLK/scratchjr-private#498
/cc @thisandagain

**Comment by chrisgarrity** [comment]
Android 4.4 is no longer supported, closing stale issue
